# Generated by Django 3.2.11 on 2022-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
