# Generated by Django 3.2.11 on 2022-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0002_product_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
