# Generated by Django 3.2.11 on 2022-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0004_service_icon_class2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
