about_information = [
    'DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE',
    'DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE',
    'DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE'
]

about_info_body = 'DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE DETAILS ABOUT YOUR SERVICE'
